### ISSUE TITLE
Szállítási probléma absztrakt modellje

### ISSUE THREAD

**Issue by piller-imre** [Bajusz15/bsc-szakdolgozat-thesis#2]
Tulajdonképpen meg kellene fogalmazni a teljes rendszer nagyvonalú modelljét. Ebben szerepelnének a drónok, mint szállítóeszközök, raktárak, kommunikációs és adatgyűjtő központok, kiszállítási helyek. (Ha egyelőre nem teljesen szakszerű, az nem probléma. Inkább arra kellene törekedni, hogy minél inkább lefedje, hogy mi is a terv az egésszel. Az implementálhatóságot szintén nem kell itt figyelembe venni, az majd később adódik.)

**Comment by piller-imre** [comment]
A modellt formalizálni kell még, értve ez alatt, hogy valahogy jelölni kellene, hogy melyik mennyiség micsoda, és a közöttük lévő ismert viszonyokat felírni.

**Comment by Bajusz15** [comment]
Miután jelöltem hogy melyik mennyiség micsoda és a viszonyokat, az optimalizáláshoz szükséges mátrixot ebből hogy írom fel?
Itt láttam egy hasonló problémát és a felírását: https://regi.tankonyvtar.hu/hu/tartalom/tamop412b2/2013-0002_kozlekedesi_uzemtan/KU/skujs533g.scorm
